FROM eclipse-temurin:17-jdk-focal
EXPOSE 5000
ADD target/sample-application-0.0.1-SNAPSHOT.jar sample-application-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "/sample-application-0.0.1-SNAPSHOT.jar"]
