version: '3.8'

services:
  app:
    image: sharath/springbootcloudinary
    build:
      context: src
      dockerfile: src/Dockerfile
    ports:
      - "5000:5000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/accountdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Dinesh@12122002
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: accountdb
      MYSQL_ROOT_PASSWORD: Dinesh@12122002
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: